name: PesenSayur
description: A new POS project.
version: 1.0.11+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^0.1.3
  flutter_icons: ^1.0.0+1
  package_info: ^0.4.1
  shared_preferences: ^0.5.6+3
  intl: ^0.16.1
  http: any
  crypto: ^2.1.3
  material_design_icons_flutter: ^4.0.5145
  cached_network_image:
  image_picker: 
  fluttercontactpicker: ^4.2.1
  audioplayers: ^0.15.1



dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true

  assets:
    - assets/